language: php

php:
  - '5.3'
  - '5.4'
  - '5.6'
  - '7.0'
  - '7.1'
  - 'nightly'
  
services:
  - mysql

env:
  - MYSQL_HOST=127.0.0.1 MYSQL_PORT=3306 MYSQL_USERNAME=root MYSQL_PASSWORD=NO_PASSWORD

before_script:
  - composer update

script:
  - ./vendor/bin/phpunit -c phpunit.xml 